export const CHAIN_ID = 80002; // Polygon Amoy

export const ADDRESSES = {
  MOCK_USDC:  "0x68eF377ea77e53b446b324fA24779aC8021aD6a6",
  ORN_PROXY:  "0x228eEe9c44d6c48A957765F2AC697733d9c3535E",
  OUSD_PROXY: "0xe631Dde195283dFF9DE0D4934361f446aD8589E5",
  DIST_PROXY: "0x5Fb00223d9Fa402760261eFb7f2F273D55B128DD",
  VAULT_PROXY:"0x57Df20982CF40d63453349a69710c3Bf6b90b820",
};

export const DEPLOYER = "0xe8239aFA5Cc7Ec80d27713A60D2E50facbeA3BC0";

export const ABIS = {
  MOCK_USDC: [
    "function name() view returns (string)",
    "function symbol() view returns (string)",
    "function decimals() pure returns (uint8)",
    "function totalSupply() view returns (uint256)",
    "function balanceOf(address) view returns (uint256)",
    "function allowance(address owner, address spender) view returns (uint256)",
    "function approve(address spender, uint256 value) returns (bool)",
    "function transfer(address to, uint256 value) returns (bool)",
    "function mint(address to, uint256 amount)",
  ],

  OUSD: [
    "function name() view returns (string)",
    "function symbol() view returns (string)",
    "function decimals() view returns (uint8)",
    "function totalSupply() view returns (uint256)",
    "function balanceOf(address) view returns (uint256)",
    "function allowance(address owner, address spender) view returns (uint256)",
    "function approve(address spender, uint256 value) returns (bool)",
    "function transfer(address to, uint256 value) returns (bool)",
    "function treasury() view returns (address)",
    "function collateralToken() view returns (address)",
    "function collateralReserves() view returns (uint256)",
    "function collateralRatio() view returns (uint256)",
    "function getPegStatus() view returns (uint256 price, bool healthy)",
    "function paused() view returns (bool)",
    "function pause()",
    "function unpause()",
    "function mint(uint256 amount)",
    "function burn(uint256 amount)",
    "function mintWithCollateral(uint256 collateralAmount)",
    "function redeem(uint256 ousdAmount)",
    "function updateTreasury(address newTreasury)",
  ],

  ORN: [
    "function name() view returns (string)",
    "function symbol() view returns (string)",
    "function decimals() view returns (uint8)",
    "function totalSupply() view returns (uint256)",
    "function balanceOf(address) view returns (uint256)",
    "function allowance(address owner, address spender) view returns (uint256)",
    "function approve(address spender, uint256 value) returns (bool)",
    "function transfer(address to, uint256 value) returns (bool)",
    "function treasury() view returns (address)",
    "function paused() view returns (bool)",
    "function pause()",
    "function unpause()",
    "function mint(uint256 amount)",
    "function burn(uint256 amount)",
    "function updateTreasury(address newTreasury)",
  ],

  DIST: [
    "function orionToken() view returns (address)",
    "function orionCoin() view returns (address)",
    "function getTokenBalance(address wallet, string tokenType) view returns (uint256)",
    "function paused() view returns (bool)",
    "function pause()",
    "function unpause()",
    "function transferToken(address recipient, uint256 amount, string tokenType)",
    "function withdrawTokens(uint256 amount, string tokenType)",
    "function burnTokens(uint256 amount, string tokenType)",
  ],

  VAULT: [
    "function vaultAdmin() view returns (address)",
    "function distributionContract() view returns (address)",
    "function orionToken() view returns (address)",
    "function stableCoin() view returns (address)",
    "function requiredApprovals() view returns (uint256)",
    "function isSigner(address) view returns (bool)",
    "function paused() view returns (bool)",
    "function pauseRequest() view returns (bool pause, uint256 approvals, bool executed)",
    "function hasApproved(uint256 txId, address signer) view returns (bool)",
    "function hasApprovedPause(address signer) view returns (bool)",
    "function getVaultBalance(address token) view returns (uint256)",
    "function transactions(uint256) view returns (address to, uint256 amount, address token, uint256 approvals, bool executed)",
    "function submitTransaction(uint256 amount, address token)",
    "function approveTransaction(uint256 txId)",
    "function requestPauseUnpause(bool pause)",
    "function approvePauseUnpause()",
    "function revokeApproval()",
    "function burnTokens(uint256 amount, string tokenType)",
    "function addSigner(address newSigner)",
    "function removeSigner(address signerToRemove)",
    "function setDistributionContract(address)",
    "function setOrionToken(address)",
    "function setStableCoin(address)",
    "function setVaultAdmin(address)",
  ],
};
